export const QUEST_LIST_REQUEST = 'QUEST_LIST_REQUEST'
export const QUEST_LIST_SUCCESS = 'QUEST_LIST_SUCCESS'
export const QUEST_LIST_FAIL = 'QUEST_LIST_FAIL'

export const QUEST_DETAILS_REQUEST = 'QUEST_DETAILS_REQUEST'
export const QUEST_DETAILS_SUCCESS = 'QUEST_DETAILS_SUCCESS'
export const QUEST_DETAILS_FAIL = 'QUEST_DETAILS_FAIL'

export const QUEST_DELETE_REQUEST = 'QUEST_DELETE_REQUEST'
export const QUEST_DELETE_SUCCESS = 'QUEST_DELETE_SUCCESS'
export const QUEST_DELETE_FAIL = 'QUEST_DELETE_FAIL'

export const QUEST_CREATE_REQUEST = 'QUEST_CREATE_REQUEST'
export const QUEST_CREATE_SUCCESS = 'QUEST_CREATE_SUCCESS'
export const QUEST_CREATE_FAIL = 'QUEST_CREATE_FAIL'
export const QUEST_CREATE_RESET = 'QUEST_CREATE_RESET'


export const QUEST_UPDATE_REQUEST = 'QUEST_UPDATE_REQUEST'
export const QUEST_UPDATE_SUCCESS = 'QUEST_UPDATE_SUCCESS'
export const QUEST_UPDATE_FAIL = 'QUEST_UPDATE_FAIL'
export const QUEST_UPDATE_RESET = 'QUEST_UPDATE_RESET'