# Generated by Django 4.1.7 on 2023-03-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chest_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chest_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoulder_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoulder_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sleeve_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sleeve_min',
        ),
    ]
