# Generated by Django 4.1.7 on 2023-03-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='value',
        ),
    ]
