# Generated by Django 4.1.7 on 2023-03-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/ts.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.IntegerField(),
        ),
    ]
