# Generated by Django 4.1.7 on 2023-03-10 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_product_image_alter_product_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Quest',
        ),
    ]
