# Generated by Django 4.1.7 on 2023-03-10 00:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_rename_product_quest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Product',
        ),
    ]
